version: '2'
services:
  php:
    build: ./docker/php
    image: jasonraimondi/php:7.1-fpm
    volumes:
     - ./logs/php:/var/log
     - ./application:/var/www/html
    networks:
     - appnet
  nginx:
    build: ./docker/nginx
    image: jasonraimondi/nginx:11.1
    ports:
      - "80:80"
      - "443:443"
    volumes:
     - ./logs/nginx:/var/log
     - ./application:/var/www/html
    networks:
     - appnet
  cron:
    build: ./docker/cron
    image: jasonraimondi/cron:latest
    volumes:
     - ./logs/cron:/var/log
     - ./application:/var/www/html
    networks:
     - appnet
  mysql:
    build: ./docker/mysql  
    image: jasonraimondi/percona:5.7
    ports:
     - "33307:3306"
    env_file: environment
    volumes:
     - ./logs/mysql:/var/log    
     - ./database:/var/lib/mysql
    networks:
     - appnet
  # mailcatcher:
  #   image: jasonraimondi/mailcatcher:latest
  #   ports:
  #    - "1081:1080"
  #    - "1026:1025"
  #   networks:
  #    - appnet
  # yarn:
  #   image: jasonraimondi/yarn:latest
  #   volumes:
  #    - ./application:/var/www/html
  #   networks:
  #    - appnet
  # redis:
  #   image: redis:latest
  #   networks:
  #    - appnet
networks:
  appnet:
    driver: "bridge"
volumes:
  data:
    driver: "local"
