version: '2'
services:
  app:
    image: jasonraimondi/app:latest
    ports:
      - "80:80"
      - "443:443"
      - "9001:9000"
    volumes:
     - ./logs:/var/log/nginx
     - ./application:/var/www/html
    networks:
     - appnet
  mailcatcher:
    image: jasonraimondi/mailcatcher:latest
    ports:
     - "1080:1080"
     - "1025:1025"
    networks:
     - appnet
  redis:
    image: redis:alpine
    networks:
     - appnet
  mysql:
    image: percona:5.7
    ports:
     - "33306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: homestead
      MYSQL_USER: homestead
      MYSQL_PASSWORD: secret
    volumes:
     - ./data:/var/lib/mysql
    networks:
     - appnet
networks:
  appnet:
    driver: "bridge"
volumes:
  data:
    driver: "local"
