version: '2'
services:
  nginx:
    image: jasonraimondi/nginx:latest
    ports:
     - "8080:80"
    volumes:
     - ./application:/var/www/html
    networks:
     - appnet
  php:
    image: jasonraimondi/php:latest
    volumes:
     - ./application:/var/www/html
    networks:
     - appnet
  mailcatcher:
    image: jasonraimondi/mailcatcher:latest
    ports:
     - "1080:1080"
     - "1025:1025"
    networks:
     - appnet
  redis:
    image: redis:alpine
    networks:
     - appnet
  db:
    image: percona:5.7
    ports:
     - "33306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: homestead
      MYSQL_USER: homestead
      MYSQL_PASSWORD: secret
    volumes:
     - ./data:/var/lib/mysql
    networks:
     - appnet
networks:
  appnet:
    driver: "bridge"
volumes:
  data:
    driver: "local"
